# Google TTS Configuration
google_tts:
  # API Configuration
  api_key: "AIzaSyDSUgjxHZiuENPHrHJl9nbLb0uAc6Vdz1M"

  # Default settings
  default_voice: "Kore"
  default_language: "en-US"
  output_format: "wav"
  sample_rate: 24000
  
  # All available voices with descriptions
  voices:
    - name: "Zephyr"
      description: "Bright"

    - name: "Puck"
      description: "Upbeat"

    - name: "Charon"
      description: "Informative"

    - name: "Kore"
      description: "Firm"

    - name: "Fenrir"
      description: "Excitable"

    - name: "Leda"
      description: "Youthful"

    - name: "Orus"
      description: "Firm"

    - name: "Aoede"
      description: "Breezy"

    - name: "Callirrhoe"
      description: "Easy-going"

    - name: "Autonoe"
      description: "Bright"

    - name: "Enceladus"
      description: "Breathy"

    - name: "Iapetus"
      description: "Clear"

    - name: "Umbriel"
      description: "Easy-going"

    - name: "Algieba"
      description: "Smooth"

    - name: "Despina"
      description: "Smooth"

    - name: "Erinome"
      description: "Clear"

    - name: "Algenib"
      description: "Gravelly"

    - name: "Rasalgethi"
      description: "Informative"

    - name: "Laomedeia"
      description: "Upbeat"

    - name: "Achernar"
      description: "Soft"

    - name: "Alnilam"
      description: "Firm"

    - name: "Schedar"
      description: "Even"

    - name: "Gacrux"
      description: "Mature"

    - name: "Pulcherrima"
      description: "Forward"

    - name: "Achird"
      description: "Friendly"

    - name: "Zubenelgenubi"
      description: "Casual"

    - name: "Vindemiatrix"
      description: "Gentle"

    - name: "Sadachbia"
      description: "Lively"

    - name: "Sadaltager"
      description: "Knowledgeable"

    - name: "Sulafat"
      description: "Warm"
